sources:
  # Have an RTSP stream? Uncomment and enter the URL for your RTSP camera.
  - type: rtsp
    name: 'Northbound'
    url: 'rtsp://rtsp://<your camera>'
    # How often an image should be captured. 
    # Increments are in seconds. Fractional values (i.e. "0.5") can be used for sub-second capturing.
    captureInterval: 1
  # Have a video file you want to process? Uncomment and enter the path of your video
  # - type: file
  #   name: 'Southbound'
  #   file: ./<path to your video file>
  #   captureInterval: 1

# Globally applied filters
# Filter jpeg frames. Currently 'motion' and 'mask' filters are available.
# Filters are processed in the order they are defined
filters:
  # Masks out a portion of the frame. Note that any pixels within the mask
  # cannot be used for detection.
  - type: mask
    # Optional. Outputs an image to the './data' path
    # debug: true
    shapes:
      # Shapes are a series of x/y coordinates
      - 1267,0,1920,0,1920,100,1267,100 # Timestamp, top right
  # Crops the frame down to the largest area of motion detection
  - type: motion
    # Optional. Outputs an image to the './data' path
    # debug: true
  
openALPR:
  # Path to ALPRToHTTP server
  url: http://open-alpr-http-wrapper:3000/detect

# Record detected license plate information
recorders:
  # Output to a SQLite database to './data'
  - type: sqlite
  # Output to an MQTT host
  # - type: mqtt
  #   url: <URL to your MQTT instance>
  #   # Optional - Default base topic is 'plate-minder'
  #   baseTopic: plate-minder
  #   # Optional - Home Assistant Auto Discovery support.
  #   hassDiscovery:
  #     # discoveryPrefix: homeassistant
  #   # Connection options can be found here: https://github.com/mqttjs/MQTT.js#client
  #   mqttOptions:
  #     username: username
  #     password: mypassword
  # Output files to a folder
  # - type: file
  #   # Naming pattern of files to store.
  #   # Tokens ({{DATE}}, {{TIME}}, {{SOURCE}}, and {{PLATE}}) are replaced with dynamic values
  #   pattern: './data/images/{{DATE}}/{{SOURCE}}/{{TIME}}_{{PLATE}}.jpeg'
  #   # Files older than retainDays will be removed.
  #   retainDays: 30
