version: "3.9"
services:
  plate-minder:
    container_name: plate-minder
    restart: unless-stopped
    image: sclaflin/plate-minder:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Set's the docker container to the host container local time
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    # For Intel related hardware acceleration, the container needs the same
    # group id as /dev/dri/renderD128.
    user: 1000:107
    devices:
      # For Intel related hardware acceleration
      - /dev/dri/renderD128
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
  plate-minder-web:
    container_name: plate-minder-web
    image: sclaflin/plate-minder-web:latest
    restart: unless-stopped
    ports:
      - 8081:80
