version: "3.9"
services:
  plate-minder:
    container_name: plate-minder
    restart: unless-stopped
    image: sclaflin/plate-minder:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Set's the docker container to the host container local time
      - /etc/localtime:/etc/localtime:ro
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
  open-alpr-http-wrapper:
    container_name: open-alpr-http-wrapper
    restart: unless-stopped
    image: sclaflin/open-alpr-http-wrapper:latest
  plate-minder-web:
    container_name: plate-minder-web
    image: sclaflin/plate-minder-web:latest
    restart: unless-stopped
    # By default, Web UI looks for plate-minder's REST service at
    # http://localhost:4000 You can override this by mounting your own
    # "plate-minder-url" file below. Contents of "plate-minder-url" must be the
    # URL you want the Web UI to connect to. For example,
    # "http://my-docker-host:4000" volumes:
    #   - ./plate-minder-url:/usr/share/nginx/html/plate-minder-url
    ports:
      - 8081:80
